import { useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { Screen } from '@/components/Screen'; import { PageHeader } from '@/components/PageHeader'; import { Card } from '@/components/Card'; import { AppText } from '@/components/AppText'; import { Field } from '@/components/Field'; import { Button } from '@/components/Button';
import { enviarFeedback, type FeedbackType } from '@/lib/feedbackApi'; import { useAuth } from '@/providers/AuthProvider'; import { colors, fonts, radii } from '@/theme';

const FAQ = [
  ['Onde fica minha compra em andamento?', 'Ela fica somente neste aparelho até ser finalizada. Suas listas e seu histórico continuam sincronizados com a conta.'],
  ['Posso usar a mesma conta do site?', 'Sim. O app usa o mesmo Supabase Auth e os mesmos dados sincronizados do Liste & Compre Web.'],
  ['O que acontece com itens que não comprei?', 'Antes de finalizar, você pode apagá-los ou transferi-los para outra lista salva.'],
  ['Posso adicionar algo que não estava planejado?', 'Sim. Use “Adicionar item extra” durante a compra. O histórico identifica esses gastos separadamente.'],
];

export default function HelpScreen() {
  const { user } = useAuth(); const [open, setOpen] = useState<number | null>(0); const [type, setType] = useState<FeedbackType>('Elogio'); const [message, setMessage] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false);
  async function send() { setBusy(true); setStatus(''); try { await enviarFeedback(type, message, user?.email ?? ''); setMessage(''); setStatus('Mensagem enviada. Obrigado pelo retorno!'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Não foi possível enviar.'); } finally { setBusy(false); } }
  return <Screen><PageHeader title="Central de Ajuda" subtitle="Orientações e contato sem sair do aplicativo." back /><AppText style={styles.section}>Perguntas frequentes</AppText>{FAQ.map(([question, answer], index) => <Pressable key={question} onPress={() => setOpen(open === index ? null : index)}><Card style={styles.faq}><View style={styles.faqHead}><AppText style={styles.question}>{question}</AppText><AppText style={styles.toggle}>{open === index ? '−' : '+'}</AppText></View>{open === index ? <AppText style={styles.answer}>{answer}</AppText> : null}</Card></Pressable>)}<AppText style={styles.section}>Fale com a gente</AppText><Card style={{ gap: 12 }}><View style={styles.types}>{(['Elogio','Reclamação','Bug'] as FeedbackType[]).map((item) => <Pressable key={item} onPress={() => setType(item)} style={[styles.type, type === item && styles.typeSelected]}><AppText style={[styles.typeText, type === item && styles.typeTextSelected]}>{item}</AppText></Pressable>)}</View><Field label="Mensagem" value={message} onChangeText={setMessage} multiline maxLength={5000} placeholder="Conte o que aconteceu ou o que podemos melhorar." style={{ minHeight: 120, textAlignVertical: 'top', paddingTop: 12 }} />{status ? <AppText accessibilityRole="alert" style={{ color: status.startsWith('Mensagem') ? colors.success : colors.danger, fontFamily: fonts.semibold, fontSize: 11 }}>{status}</AppText> : null}<Button label="Enviar feedback" loading={busy} disabled={!message.trim()} onPress={() => void send()} /></Card></Screen>;
}
const styles = StyleSheet.create({ section: { fontFamily: fonts.black, fontSize: 18, marginTop: 8, marginBottom: 8 }, faq: { padding: 13, marginBottom: 8, borderRadius: radii.md }, faqHead: { flexDirection: 'row', alignItems: 'center', gap: 8 }, question: { flex: 1, fontFamily: fonts.semibold, fontSize: 12 }, toggle: { fontFamily: fonts.black, fontSize: 20, color: colors.orange }, answer: { color: colors.muted, fontSize: 10, lineHeight: 16, marginTop: 8 }, types: { flexDirection: 'row', gap: 7 }, type: { flex: 1, minHeight: 44, borderWidth: 2, borderColor: colors.navy, borderRadius: radii.pill, alignItems: 'center', justifyContent: 'center' }, typeSelected: { backgroundColor: colors.navy }, typeText: { fontFamily: fonts.semibold, fontSize: 10 }, typeTextSelected: { color: colors.white }, });
