import { useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { Screen } from '@/components/Screen'; import { PageHeader } from '@/components/PageHeader'; import { Card } from '@/components/Card'; import { AppText } from '@/components/AppText'; import { ItemForm, type ItemFormValue } from '@/components/ItemForm'; import { Button } from '@/components/Button'; import { BottomSheet } from '@/components/BottomSheet'; import { Field } from '@/components/Field';
import { useCloud } from '@/providers/CloudProvider'; import { gerarId } from '@/domain/purchase'; import { dataPrevistaValida, normalizarDataPrevista } from '@/domain/list'; import { colors, fonts, radii } from '@/theme';

export default function ListBuilderScreen() {
  const cloud = useCloud(); const { itens, historico, edicaoId } = cloud.data;
  const [saveOpen, setSaveOpen] = useState(false); const [listName, setListName] = useState(''); const [plannedDate, setPlannedDate] = useState(''); const [saveError, setSaveError] = useState('');
  const [itemToRemove, setItemToRemove] = useState<string | null>(null); const [clearOpen, setClearOpen] = useState(false);

  function add(value: ItemFormValue) { cloud.mutate((data) => { data.itens.push({ id: gerarId(), ...value, comprado: false }); }); }
  function confirmRemove() { if (!itemToRemove) return; cloud.mutate((data) => { data.itens = data.itens.filter((item) => item.id !== itemToRemove); }); setItemToRemove(null); }
  function save() { if (!itens.length) return; if (edicaoId) { cloud.mutate((data) => { const current = data.historico.find((list) => list.id === edicaoId); if (current) { current.itens = structuredClone(data.itens); current.data = new Date().toISOString(); } data.itens = []; data.edicaoId = null; }); router.replace('/(tabs)/listas'); return; } setListName(''); setPlannedDate(''); setSaveError(''); setSaveOpen(true); }
  function confirmSave() { const clean = listName.trim(); if (!clean) { setSaveError('Informe um nome para a lista.'); return; } if (clean.length > 200) { setSaveError('O nome da lista é muito longo.'); return; } if (historico.some((list) => list.nome.toLowerCase() === clean.toLowerCase())) { setSaveError('Já existe uma lista com esse nome.'); return; } const date = plannedDate.trim(); if (!dataPrevistaValida(date)) { setSaveError('Use uma data válida no formato AAAA-MM-DD.'); return; } const normalizedDate = normalizarDataPrevista(date); cloud.mutate((data) => { data.historico.push({ id: gerarId(), nome: clean, itens: structuredClone(data.itens), data: new Date().toISOString(), ...(normalizedDate ? { dataPrevista: normalizedDate } : {}) }); data.itens = []; data.edicaoId = null; }); setSaveOpen(false); router.replace('/(tabs)/listas'); }
  function confirmClear() { cloud.mutate((data) => { data.itens = []; data.edicaoId = null; }); setClearOpen(false); }

  const pendingItem = itens.find((item) => item.id === itemToRemove);

  return <Screen><PageHeader title={edicaoId ? 'Editar lista' : 'Crie sua lista'} subtitle="Adicione os produtos antes de ir às compras." back /><Card style={{ marginBottom: 14 }}><ItemForm onSubmit={add} /></Card><View style={styles.header}><AppText style={styles.heading}>{itens.length} {itens.length === 1 ? 'item' : 'itens'}</AppText>{itens.length ? <Pressable onPress={() => setClearOpen(true)}><AppText style={styles.clear}>Limpar</AppText></Pressable> : null}</View>{itens.map((item) => <Card key={item.id} style={styles.item}><View style={{ flex: 1 }}><AppText style={styles.itemName}>{item.nome}</AppText><AppText style={styles.itemMeta}>{item.categoria} · {item.tipo === 'Kg' ? `${item.quantidade.toLocaleString('pt-BR', { minimumFractionDigits: 3 })} kg` : `${item.quantidade} un`}</AppText></View><Pressable accessibilityLabel={`Excluir ${item.nome}`} onPress={() => setItemToRemove(item.id)} style={styles.remove}><AppText style={styles.removeText}>×</AppText></Pressable></Card>)}{!itens.length ? <Card><AppText style={styles.empty}>Sua lista está vazia. Comece adicionando um produto acima.</AppText></Card> : null}<Button label={edicaoId ? 'Salvar alterações' : 'Salvar lista'} onPress={save} disabled={!itens.length} style={{ marginTop: 16 }} />

  <BottomSheet visible={saveOpen} onClose={() => setSaveOpen(false)}><AppText style={styles.sheetTitle}>Salvar nova lista</AppText><Field label="Nome da lista" value={listName} onChangeText={(value) => { setListName(value); setSaveError(''); }} autoCapitalize="sentences" maxLength={200} autoFocus /><Field label="Data prevista (opcional)" value={plannedDate} onChangeText={(value) => { setPlannedDate(value.replace(/[^0-9-]/g, '').slice(0, 10)); setSaveError(''); }} keyboardType="numbers-and-punctuation" placeholder="AAAA-MM-DD" maxLength={10} style={{ marginTop: 10 }} />{saveError ? <AppText accessibilityRole="alert" style={styles.error}>{saveError}</AppText> : null}<Button label="Salvar lista" onPress={confirmSave} disabled={!listName.trim()} style={{ marginTop: 12 }} /><Button label="Cancelar" variant="ghost" onPress={() => setSaveOpen(false)} /></BottomSheet>

  <BottomSheet visible={Boolean(itemToRemove)} onClose={() => setItemToRemove(null)}><AppText style={styles.sheetTitle}>Remover item?</AppText><AppText style={styles.sheetText}>{pendingItem ? `“${pendingItem.nome}” será retirado desta lista.` : 'O item será retirado desta lista.'}</AppText><Button label="Remover item" variant="dangerOutline" onPress={confirmRemove} style={{ marginTop: 8 }} /><Button label="Cancelar" variant="secondary" onPress={() => setItemToRemove(null)} style={{ marginTop: 8 }} /></BottomSheet>

  <BottomSheet visible={clearOpen} onClose={() => setClearOpen(false)}><AppText style={styles.sheetTitle}>Limpar lista?</AppText><AppText style={styles.sheetText}>Todos os itens da lista em criação serão removidos. Essa ação não pode ser desfeita.</AppText><Button label="Limpar lista" variant="dangerOutline" onPress={confirmClear} style={{ marginTop: 8 }} /><Button label="Cancelar" variant="secondary" onPress={() => setClearOpen(false)} style={{ marginTop: 8 }} /></BottomSheet>
  </Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }, heading: { fontFamily: fonts.bold, fontSize: 16 }, clear: { color: colors.danger, fontFamily: fonts.semibold, padding: 8 }, item: { flexDirection: 'row', alignItems: 'center', padding: 13, marginBottom: 8, borderRadius: radii.md }, itemName: { fontFamily: fonts.bold, fontSize: 14 }, itemMeta: { color: colors.muted, fontSize: 10, marginTop: 2 }, remove: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' }, removeText: { color: colors.danger, fontFamily: fonts.bold, fontSize: 26 }, empty: { color: colors.muted, textAlign: 'center', paddingVertical: 10 }, sheetTitle: { fontFamily: fonts.black, fontSize: 21, marginBottom: 10 }, sheetText: { color: colors.muted, fontSize: 12, lineHeight: 18, marginBottom: 6 }, error: { color: colors.danger, fontFamily: fonts.semibold, fontSize: 11, marginTop: 7 } });
