import { useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { Screen } from '@/components/Screen'; import { TabTopBar } from '@/components/TabTopBar'; import { PageHeader } from '@/components/PageHeader'; import { Card } from '@/components/Card'; import { AppText } from '@/components/AppText'; import { BottomSheet } from '@/components/BottomSheet'; import { Button } from '@/components/Button';
import { useCloud } from '@/providers/CloudProvider'; import { itensParaRefazerCompra } from '@/domain/purchase'; import type { CompraFinalizada } from '@/types'; import { colors, fonts, radii } from '@/theme';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });

export default function HistoryTab() {
  const cloud = useCloud(); const purchases = cloud.data.compras; const [selected, setSelected] = useState<CompraFinalizada | null>(null); const [showItems, setShowItems] = useState(false);
  const total = useMemo(() => purchases.reduce((sum, item) => sum + item.valorTotal, 0), [purchases]);
  function repeat() { if (!selected) return; const apply = () => { cloud.mutate((data) => { data.itens = itensParaRefazerCompra(selected); data.edicaoId = null; }); setSelected(null); setShowItems(false); router.push('/lista'); }; if (cloud.data.itens.length) Alert.alert('Substituir lista em criação?', 'Os itens atuais serão substituídos pelos itens desta compra.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Substituir', style: 'destructive', onPress: apply }]); else apply(); }
  return <Screen><TabTopBar /><PageHeader title="Histórico" subtitle="Compras finalizadas, da mais recente para a mais antiga." /><Card style={styles.totalCard}><AppText style={styles.totalLabel}>Total gasto</AppText><AppText style={styles.total}>{money.format(total)}</AppText></Card>{purchases.length ? [...purchases].reverse().map((purchase) => <Pressable key={purchase.id} onPress={() => { setSelected(purchase); setShowItems(false); }}><Card style={styles.card}><View style={{ flex: 1 }}><AppText style={styles.name}>{purchase.nomeLista}</AppText><AppText style={styles.meta}>{new Date(purchase.dataFim).toLocaleString('pt-BR')}</AppText><AppText style={styles.meta}>{purchase.itens.length} itens · Extras: {money.format(purchase.gastosAdicionais)}</AppText></View><AppText style={styles.value}>{money.format(purchase.valorTotal)}</AppText></Card></Pressable>) : <Card><AppText style={styles.empty}>Nenhuma compra finalizada ainda.</AppText></Card>}<BottomSheet visible={Boolean(selected)} onClose={() => { setSelected(null); setShowItems(false); }}>{selected ? <>{showItems ? <><AppText style={styles.sheetTitle}>Itens da compra</AppText><AppText style={styles.sheetSub}>{selected.nomeLista}</AppText><View style={styles.items}>{selected.itens.map((item) => <View key={item.id} style={styles.item}><View style={{ flex: 1 }}><AppText style={styles.itemName}>{item.nome}{item.origem === 'extra' ? '  • Extra' : ''}</AppText><AppText style={styles.meta}>{item.quantidade.toLocaleString('pt-BR', { maximumFractionDigits: 3 })} {item.tipo}</AppText></View><AppText style={styles.itemValue}>{money.format(item.precoUnitario * item.quantidade)}</AppText></View>)}</View><Button label="Voltar às opções" variant="secondary" onPress={() => setShowItems(false)} /></> : <><AppText style={styles.sheetTitle}>{selected.nomeLista}</AppText><AppText style={styles.sheetSub}>O que deseja fazer com esta compra?</AppText><Button label="↻ Refazer a mesma compra" onPress={repeat} /><Button label="📋 Ver itens da compra" variant="secondary" onPress={() => setShowItems(true)} style={{ marginTop: 9 }} /><Button label="Cancelar" variant="ghost" onPress={() => setSelected(null)} /></>}</> : null}</BottomSheet></Screen>;
}
const styles = StyleSheet.create({ totalCard: { backgroundColor: colors.softOrange, marginBottom: 14 }, totalLabel: { color: colors.muted, fontFamily: fonts.semibold, fontSize: 11 }, total: { fontFamily: fonts.black, color: colors.orangeDark, fontSize: 26 }, card: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 13, marginBottom: 9, borderRadius: radii.md }, name: { fontFamily: fonts.bold, fontSize: 15 }, meta: { color: colors.muted, fontSize: 9, marginTop: 2 }, value: { fontFamily: fonts.black, color: colors.orangeDark, fontSize: 16 }, empty: { color: colors.muted, textAlign: 'center', paddingVertical: 14 }, sheetTitle: { fontFamily: fonts.black, fontSize: 22 }, sheetSub: { color: colors.muted, marginBottom: 14 }, items: { marginBottom: 14 }, item: { flexDirection: 'row', gap: 8, paddingVertical: 9, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.line }, itemName: { fontFamily: fonts.semibold, fontSize: 12 }, itemValue: { fontFamily: fonts.bold, fontSize: 12 }, });
