import { router } from 'expo-router';
import { Pressable, StyleSheet, View } from 'react-native';
import { Screen } from '@/components/Screen'; import { Brand } from '@/components/Brand'; import { Card } from '@/components/Card'; import { AppText } from '@/components/AppText';
import { useAuth } from '@/providers/AuthProvider'; import { useCloud } from '@/providers/CloudProvider'; import { colors, fonts, radii } from '@/theme';

const steps = [
  { icon: '📝', title: 'Crie sua lista', text: 'Planeje produtos, categorias e quantidades.', action: () => router.push('/lista') },
  { icon: '🛒', title: 'Faça sua compra', text: 'Acompanhe preços, itens e total no mercado.', action: () => router.push('/(tabs)/comprar') },
  { icon: '🧾', title: 'Histórico de compras', text: 'Revise gastos e refaça compras anteriores.', action: () => router.push('/(tabs)/historico') },
];

export default function HomeTab() {
  const { name } = useAuth(); const { data, status } = useCloud();
  return <Screen scroll={false} contentStyle={styles.homeContent}><Brand /><AppText style={styles.greeting}>Olá{name ? `, ${name.split(' ')[0]}` : ''}.</AppText><AppText style={styles.sub}>O que vamos organizar hoje?</AppText><View style={styles.mainGroup}><View style={styles.steps}>{steps.map((step, index) => <View key={step.title}><Pressable onPress={step.action} style={({ pressed }) => [pressed && styles.pressed]}><Card style={styles.step}><View style={styles.icon}><AppText style={{ fontSize: 26 }}>{step.icon}</AppText></View><View style={{ flex: 1 }}><AppText style={styles.title}>{step.title}</AppText><AppText style={styles.text}>{step.text}</AppText></View><AppText style={styles.arrow}>›</AppText></Card></Pressable>{index < steps.length - 1 ? <AppText style={styles.down}>↓</AppText> : null}</View>)}</View><Card style={styles.summary}><AppText style={styles.summaryTitle}>Resumo rápido</AppText><View style={styles.summaryRow}><Summary value={data.historico.length} label="listas" /><Summary value={data.compras.length} label="compras" /><Summary value={status === 'ready' ? '✓' : '…'} label="nuvem" /></View></Card></View></Screen>;
}
function Summary({ value, label }: { value: number | string; label: string }) { return <View style={styles.summaryItem}><AppText style={styles.summaryValue}>{value}</AppText><AppText style={styles.summaryLabel}>{label}</AppText></View>; }
const styles = StyleSheet.create({ homeContent: { paddingBottom: 0, position: 'relative' }, greeting: { fontFamily: fonts.black, fontSize: 30, marginTop: 4 }, sub: { color: colors.muted, marginBottom: 0 }, mainGroup: { position: 'absolute', left: 16, right: 16, bottom: 0, gap: 0 }, steps: { gap: 0 }, step: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 15 }, icon: { width: 48, height: 48, borderRadius: radii.md, backgroundColor: colors.softOrange, alignItems: 'center', justifyContent: 'center' }, title: { fontFamily: fonts.bold, fontSize: 16 }, text: { color: colors.muted, fontSize: 11, marginTop: 2 }, arrow: { fontFamily: fonts.bold, fontSize: 30 }, down: { textAlign: 'center', fontFamily: fonts.black, color: colors.orange, fontSize: 20, marginVertical: 0 }, pressed: { opacity: 0.86, transform: [{ scale: 0.99 }] }, summary: { marginTop: 0 }, summaryTitle: { fontFamily: fonts.bold, marginBottom: 12 }, summaryRow: { flexDirection: 'row', justifyContent: 'space-around' }, summaryItem: { alignItems: 'center' }, summaryValue: { fontFamily: fonts.black, fontSize: 22, color: colors.orange }, summaryLabel: { color: colors.muted, fontSize: 10 }, });
