import { Alert, Pressable, StyleSheet, View } from 'react-native'; import { router } from 'expo-router';
import { Screen } from '@/components/Screen'; import { PageHeader } from '@/components/PageHeader'; import { Card } from '@/components/Card'; import { AppText } from '@/components/AppText'; import { Button } from '@/components/Button';
import { useCloud } from '@/providers/CloudProvider'; import { colors, fonts, radii } from '@/theme';

export default function ListsTab() {
  const cloud = useCloud(); const lists = cloud.data.historico;
  function edit(id: string) { const list = lists.find((item) => item.id === id); if (!list) return; const open = () => { cloud.mutate((data) => { data.itens = structuredClone(list.itens); data.edicaoId = id; }); router.push('/lista'); }; if (cloud.data.itens.length && cloud.data.edicaoId !== id) Alert.alert('Substituir lista em criação?', 'A lista que está sendo criada será substituída.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Substituir', style: 'destructive', onPress: open }]); else open(); }
  function remove(id: string) { const list = lists.find((item) => item.id === id); if (!list) return; Alert.alert(`Excluir ${list.nome}?`, 'A lista será removida, mas compras já finalizadas continuam no histórico.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: () => cloud.mutate((data) => { data.historico = data.historico.filter((item) => item.id !== id); if (data.edicaoId === id) data.edicaoId = null; }) }]); }
  return <Screen><PageHeader title="Minhas listas" subtitle="Listas sincronizadas com a sua conta." /><Button label="+ Nova lista" onPress={() => router.push('/lista')} style={{ marginBottom: 14 }} />{lists.length ? lists.map((list) => <Card key={list.id} style={styles.card}><Pressable onPress={() => edit(list.id)} style={{ flex: 1 }}><AppText style={styles.name}>{list.nome}</AppText><AppText style={styles.meta}>{list.itens.length} {list.itens.length === 1 ? 'item' : 'itens'} · atualizada {new Date(list.data).toLocaleDateString('pt-BR')}</AppText>{list.dataPrevista ? <AppText style={styles.date}>📅 {new Date(`${list.dataPrevista}T12:00:00`).toLocaleDateString('pt-BR')}</AppText> : null}</Pressable><View style={styles.actions}><Pressable onPress={() => router.push({ pathname: '/compra/[listaId]', params: { listaId: list.id } })} style={styles.shop}><AppText style={styles.shopText}>🛒</AppText></Pressable><Pressable onPress={() => remove(list.id)} style={styles.delete}><AppText style={styles.deleteText}>×</AppText></Pressable></View></Card>) : <Card><AppText style={styles.empty}>Você ainda não salvou nenhuma lista.</AppText></Card>}</Screen>;
}
const styles = StyleSheet.create({ card: { flexDirection: 'row', alignItems: 'center', padding: 14, marginBottom: 10, borderRadius: radii.md }, name: { fontFamily: fonts.bold, fontSize: 16 }, meta: { color: colors.muted, fontSize: 10, marginTop: 2 }, date: { color: colors.orangeDark, fontFamily: fonts.semibold, fontSize: 10, marginTop: 4 }, actions: { flexDirection: 'row', marginLeft: 8 }, shop: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, shopText: { fontSize: 20 }, delete: { width: 40, height: 44, alignItems: 'center', justifyContent: 'center' }, deleteText: { color: colors.danger, fontFamily: fonts.bold, fontSize: 26 }, empty: { textAlign: 'center', color: colors.muted, paddingVertical: 16 }, });
