import { useState } from 'react';
import { Alert, Pressable, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { Screen } from '@/components/Screen'; import { PageHeader } from '@/components/PageHeader'; import { Card } from '@/components/Card'; import { AppText } from '@/components/AppText'; import { Button } from '@/components/Button'; import { BottomSheet } from '@/components/BottomSheet'; import { Field } from '@/components/Field';
import { useCloud } from '@/providers/CloudProvider'; import { dataPrevistaValida, normalizarDataPrevista } from '@/domain/list'; import type { ListaSalva } from '@/types'; import { colors, fonts, radii } from '@/theme';

export default function ListsTab() {
  const cloud = useCloud(); const lists = cloud.data.historico; const [selected, setSelected] = useState<ListaSalva | null>(null); const [name, setName] = useState(''); const [date, setDate] = useState(''); const [error, setError] = useState('');
  function openActions(list: ListaSalva) { setSelected(list); setName(list.nome); setDate(list.dataPrevista ?? ''); setError(''); }
  function edit(id: string) { const list = lists.find((item) => item.id === id); if (!list) return; const open = () => { setSelected(null); cloud.mutate((data) => { data.itens = structuredClone(list.itens); data.edicaoId = id; }); router.push('/lista'); }; if (cloud.data.itens.length && cloud.data.edicaoId !== id) Alert.alert('Substituir lista em criação?', 'A lista que está sendo criada será substituída.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Substituir', style: 'destructive', onPress: open }]); else open(); }
  function remove(id: string) { const list = lists.find((item) => item.id === id); if (!list) return; Alert.alert(`Excluir ${list.nome}?`, 'A lista será removida, mas compras já finalizadas continuam no histórico.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: () => { setSelected(null); cloud.mutate((data) => { data.historico = data.historico.filter((item) => item.id !== id); if (data.edicaoId === id) data.edicaoId = null; }); } }]); }
  function saveMetadata() { if (!selected) return; const clean = name.trim(); if (!clean) { setError('Informe um nome para a lista.'); return; } if (clean.length > 200) { setError('O nome da lista é muito longo.'); return; } if (lists.some((list) => list.id !== selected.id && list.nome.toLowerCase() === clean.toLowerCase())) { setError('Já existe outra lista com esse nome.'); return; } const cleanDate = date.trim(); if (!dataPrevistaValida(cleanDate)) { setError('Use uma data válida no formato AAAA-MM-DD.'); return; } const normalizedDate = normalizarDataPrevista(cleanDate); cloud.mutate((data) => { const list = data.historico.find((item) => item.id === selected.id); if (!list) return; list.nome = clean; list.data = new Date().toISOString(); if (normalizedDate) list.dataPrevista = normalizedDate; else delete list.dataPrevista; }); setSelected(null); }
  function startPurchase(id: string) { setSelected(null); router.push({ pathname: '/compra/[listaId]', params: { listaId: id } }); }
  return <Screen><PageHeader title="Minhas listas" subtitle="Listas sincronizadas com a sua conta." /><Button label="+ Nova lista" onPress={() => router.push('/lista')} style={{ marginBottom: 14 }} />{lists.length ? lists.map((list) => <Pressable key={list.id} onPress={() => openActions(list)}><Card style={styles.card}><View style={{ flex: 1 }}><AppText style={styles.name}>{list.nome}</AppText><AppText style={styles.meta}>{list.itens.length} {list.itens.length === 1 ? 'item' : 'itens'} · atualizada {new Date(list.data).toLocaleDateString('pt-BR')}</AppText>{list.dataPrevista ? <AppText style={styles.date}>📅 {new Date(`${list.dataPrevista}T12:00:00`).toLocaleDateString('pt-BR')}</AppText> : null}</View><AppText style={styles.chevron}>›</AppText></Card></Pressable>) : <Card><AppText style={styles.empty}>Você ainda não salvou nenhuma lista.</AppText></Card>}<BottomSheet visible={Boolean(selected)} onClose={() => setSelected(null)}>{selected ? <><AppText style={styles.sheetTitle}>Opções da lista</AppText><Field label="Nome" value={name} onChangeText={(value) => { setName(value); setError(''); }} maxLength={200} /><Field label="Data prevista (opcional)" value={date} onChangeText={(value) => { setDate(value.replace(/[^0-9-]/g, '').slice(0, 10)); setError(''); }} placeholder="AAAA-MM-DD" keyboardType="numbers-and-punctuation" maxLength={10} style={{ marginTop: 10 }} />{error ? <AppText accessibilityRole="alert" style={styles.error}>{error}</AppText> : null}<Button label="Salvar nome e data" onPress={saveMetadata} style={{ marginTop: 12 }} /><Button label="Editar itens" variant="secondary" onPress={() => edit(selected.id)} style={{ marginTop: 8 }} /><Button label="🛒 Iniciar compra" variant="secondary" onPress={() => startPurchase(selected.id)} style={{ marginTop: 8 }} /><Button label="Excluir lista" variant="danger" onPress={() => remove(selected.id)} style={{ marginTop: 8 }} /><Button label="Cancelar" variant="ghost" onPress={() => setSelected(null)} /></> : null}</BottomSheet></Screen>;
}
const styles = StyleSheet.create({ card: { flexDirection: 'row', alignItems: 'center', padding: 14, marginBottom: 10, borderRadius: radii.md }, name: { fontFamily: fonts.bold, fontSize: 16 }, meta: { color: colors.muted, fontSize: 10, marginTop: 2 }, date: { color: colors.orangeDark, fontFamily: fonts.semibold, fontSize: 10, marginTop: 4 }, chevron: { fontFamily: fonts.bold, fontSize: 28 }, empty: { textAlign: 'center', color: colors.muted, paddingVertical: 16 }, sheetTitle: { fontFamily: fonts.black, fontSize: 21, marginBottom: 10 }, error: { color: colors.danger, fontFamily: fonts.semibold, fontSize: 11, marginTop: 7 } });
